Repository AY2223S1-CS2103T-W08-4/tp, pull requests merged in 2022-10, with the labels that each got.

#78 Add SplitView feature for GUI
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TaskListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TaskListCard.fxml
  src/main/resources/view/TaskListPanel.fxml
Labels: priority.High, type.Enhancement, type.Task

#80 Feature skeletal task data
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyTaskList.java
  src/main/java/seedu/address/model/TaskList.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/storage/JsonSerializableTaskList.java
  src/main/java/seedu/address/storage/JsonTaskStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/TaskStorage.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/java/seedu/address/ui/TaskListPanel.java
  src/main/resources/view/TaskListCard.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
Labels: priority.High, type.Task

#82 Add headers to both Task and Supplier panes
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: priority.Medium, type.Enhancement

#86 Add MarkTaskCommand for marking tasks as done
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/MarkTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/MarkTaskCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TaskList.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedTask.java
  src/main/java/seedu/address/storage/JsonSerializableTaskList.java
  src/main/java/seedu/address/storage/JsonTaskStorage.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TaskListCard.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/MarkTaskCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/TaskBuilder.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: priority.High, type.Task

#88 Fix the issue where TaskList's ObservableList is not updating
  src/main/java/seedu/address/model/TaskList.java
Labels: priority.High, type.Bug, severity.High

#93 Implement functionality for supplier commands and test cases
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Item.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Price.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Task

#94 Edited SampleDataUtil to adapt to Suppliers and added Supplier tag
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.Medium

#92 Add addTask feature to codebase
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/TaskList.java
  src/main/java/seedu/address/model/task/Task.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/AddTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.High, type.Task

#100 Edited IsSamePerson and adapted PersonTest cases
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Item.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/Price.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: priority.Medium

#99 Update Developer Guide to reflect Task-related Components
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/Ui.png
  docs/images/UiClassDiagram.png
Labels: priority.High, type.Task

#101 Update edit command and test cases
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: type.Story, priority.High

#103 Add PriceTest and ItemTest files and cases
  docs/index.md
  src/main/java/seedu/address/model/person/Item.java
  src/main/java/seedu/address/model/person/Price.java
  src/test/java/seedu/address/model/person/ItemTest.java
  src/test/java/seedu/address/model/person/PriceTest.java
Labels: priority.High

#105 Edited UG to match Supplier commands
  docs/UserGuide.md
Labels: priority.High

#122 Add testcase for AddTaskCommand class and AddTaskCommandParser class
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddTaskCommandParserTest.java
Labels: priority.High

#124 Added test case for Delete and Update task command
  src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java
  src/main/java/seedu/address/logic/commands/UpdateTaskCommand.java
  src/main/java/seedu/address/logic/parser/UpdateTaskCommandParser.java
  src/main/java/seedu/address/model/TaskList.java
  src/main/java/seedu/address/model/task/Task.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteTaskCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UpdateTaskCommandParserTest.java
  src/test/java/seedu/address/model/task/TaskListTest.java
  src/test/java/seedu/address/model/task/TaskTest.java
  src/test/java/seedu/address/testutil/UpdateTaskDescriptorBuilder.java
Labels: priority.High, type.Task

#121 Add Inventory storage for Salesy
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/util/IntegerUtil.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Inventory.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyInventory.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/item/SupplyItem.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/InventoryStorage.java
  src/main/java/seedu/address/storage/JsonAdaptedSupplyItem.java
  src/main/java/seedu/address/storage/JsonInventoryStorage.java
  src/main/java/seedu/address/storage/JsonSerializableInventory.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/InventoryPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/SupplyItemCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/InventoryPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/SupplyItemCard.fxml
  src/test/data/JsonInventoryStorageTest/invalidAndValidSupplyItemInventory.json
  src/test/data/JsonInventoryStorageTest/invalidSupplyItemInventory.json
  src/test/data/JsonInventoryStorageTest/notJsonFormatInventory.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/UnMarkTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateTaskCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedSupplyItemTest.java
  src/test/java/seedu/address/storage/JsonInventoryStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/SupplyItemBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/TypicalSupplyItems.java
Labels: priority.High, type.Task

#126 Test classes for SuppyItem and Inventory classes added
  src/main/java/seedu/address/model/Inventory.java
  src/main/java/seedu/address/model/item/SupplyItem.java
  src/test/java/seedu/address/model/item/InventoryTest.java
  src/test/java/seedu/address/model/item/SupplyItemTest.java
Labels: priority.High

#128 Add commands to list all storage types
  src/main/java/seedu/address/logic/commands/ListAllCommand.java
  src/main/java/seedu/address/logic/commands/ListInventoryCommand.java
  src/main/java/seedu/address/logic/commands/ListSupplierCommand.java
  src/main/java/seedu/address/logic/commands/ListTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ListInventoryCommandTest.java
  src/test/java/seedu/address/logic/commands/ListSupplierCommandTest.java
  src/test/java/seedu/address/logic/commands/ListTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: priority.High, type.Task

#127 Update supplier find command
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/ItemContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: priority.Medium, type.Enhancement

#132 Rough outline for proposed implementation of addItem feature
  docs/DeveloperGuide.md
  docs/diagrams/AddItemActivityDiagram.puml
  docs/diagrams/AddItemState0.puml
  docs/diagrams/AddItemState1.puml
  docs/images/AddItemActivityDiagram.png
  docs/images/AddItemState0-Initial_state.png
  docs/images/AddItemState1-Initial_state.png
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: priority.High, type.Enhancement

#131 Add rough outline of implementaion walkthrough (Mark/Unmark Tasks)
  docs/DeveloperGuide.md
  docs/diagrams/MarkTaskActivityDiagram.puml
  docs/diagrams/MarkTaskState0.puml
  docs/diagrams/MarkTaskState1.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/MarkTaskActivityDiagram.png
  docs/images/MarkTaskState0.png
  docs/images/MarkTaskState1.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  src/main/java/seedu/address/storage/JsonSerializableTaskList.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: priority.High, type.Enhancement

#136 Make changes to examples to match suppliers
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: priority.Low, severity.VeryLow

#138 Update User Guide with new style format and details regarding user co…
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/UpdateTaskCommand.java
Labels: priority.High, type.Enhancement, type.Task

#139 Add unit and integration tests for Inventory and related components
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/ui/SupplyItemCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StatsCard.fxml
  src/test/data/JsonSerializableInventoryTest/invalidInventory.json
  src/test/data/JsonSerializableInventoryTest/typicalInventory.json
  src/test/java/seedu/address/storage/JsonSerializableInventoryTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Task

#143 Refactor code for tag to be optional for addTask
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/AddTaskCommandParserTest.java
Labels: priority.High, type.Task

#144 Add rough outline of AddTaskCommand into Developer's guide
  docs/DeveloperGuide.md
  docs/diagrams/AddTaskActivityDiagram.puml
  docs/images/AddTaskActivityDiagram.png
Labels: priority.High, type.Enhancement

#141 Add information to Stats panel
  src/main/java/seedu/address/commons/util/StockUtil.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatsCard.java
  src/main/java/seedu/address/ui/SupplyItemCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StatsCard.fxml
  src/main/resources/view/TaskListCard.fxml
  src/test/java/seedu/address/commons/util/StockUtilTest.java
Labels: priority.Medium, type.Task

#145 Add date check for addTask and editTask parsers
  docs/DeveloperGuide.md
  docs/images/Ui.png
  src/main/java/seedu/address/commons/util/DateUtil.java
  src/main/java/seedu/address/logic/commands/AddTaskCommand.java
  src/main/java/seedu/address/logic/commands/UpdateTaskCommand.java
  src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java
  src/main/java/seedu/address/logic/parser/UpdateTaskCommandParser.java
  src/main/java/seedu/address/ui/StatsCard.java
  src/main/resources/view/StatsCard.fxml
  src/test/java/seedu/address/commons/util/DateUtilTest.java
  src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/UpdateTaskCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.High, type.Enhancement

#149 Add safer handling to method
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/ui/StatsCard.java
Labels: priority.High, type.Bug, severity.High

#147 Rough AddItem command for now
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddItemCommand.java
  src/main/java/seedu/address/logic/parser/AddItemCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/item/SupplyItem.java
  src/test/java/seedu/address/model/item/SupplyItemTest.java
Labels: priority.High

#153 Added Test cases for AddItemCommand and AddItemCommandParser
  src/main/java/seedu/address/logic/commands/AddItemCommand.java
  src/main/java/seedu/address/logic/parser/AddItemCommandParser.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/data/JsonSerializableInventoryTest/typicalInventory.json
  src/test/java/seedu/address/logic/commands/AddItemCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddItemCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, severity.Medium

#152 Change TextField behaviour from onAction to onMouseOut
  docs/images/Ui.png
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditStockCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditStockCommandParser.java
  src/main/java/seedu/address/model/item/SupplyItem.java
  src/main/java/seedu/address/ui/SupplyItemCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/SupplyItemCard.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditStockCommandTest.java
  src/test/java/seedu/address/logic/commands/ListAllCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditStockCommandParserTest.java
  src/test/java/seedu/address/model/item/InventoryTest.java
  src/test/java/seedu/address/model/item/SupplyItemTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/EditStockDescriptorBuilder.java
Labels: priority.Medium, type.Enhancement

#155 Updated README to resemble a product landing page
  README.md
  docs/index.md
Labels: type.Task, Docs

#156 Sort list of tasks and display them by earlier deadline first.
  src/main/java/seedu/address/model/ReadOnlyTaskList.java
  src/main/java/seedu/address/model/TaskList.java
  src/test/java/seedu/address/logic/commands/MarkTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/UnMarkTaskCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateTaskCommandTest.java
  src/test/java/seedu/address/model/task/TaskListTest.java
  src/test/java/seedu/address/testutil/TypicalTasks.java
Labels: priority.High, type.Task

#159 Update DG regarding edit supplier command
  docs/DeveloperGuide.md
  docs/diagrams/EditCommandSummaryActivityDiagram.puml
  docs/diagrams/SupplierAndSupplyItemClassDiagram.puml
  docs/images/EditCommandSummaryActivityDiagram.png
  docs/images/SupplierAndSupplyItemClassDiagram.png
Labels: Docs

#158 Fix bug in edit command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditItemSupplierCommand.java
  src/test/java/seedu/address/logic/commands/EditItemSupplierCommandTest.java
Labels: type.Bug, severity.High

#157 Refine DG for Ui
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.High, type.Task, severity.VeryLow

#160 Updated UG
  docs/UserGuide.md
Labels: priority.Medium, type.Enhancement

#162 Fix for Ui bug regarding elipsis due to initial onAction
  src/main/java/seedu/address/ui/InventoryPanel.java
  src/main/java/seedu/address/ui/SupplyItemCard.java
  src/main/resources/view/SupplyItemCard.fxml
Labels: priority.Medium, type.Bug, severity.Medium

#164 Add a command to enable refreshing of stats panel on increment and decrement
  src/main/java/seedu/address/logic/commands/RefreshStatsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/InventoryPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/SupplyItemCard.java
  src/test/java/seedu/address/logic/commands/RefreshStatsCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.High, type.Bug, severity.Medium

#165 Change default action of TextField to resemble form submission
  src/main/java/seedu/address/ui/SupplyItemCard.java
  src/main/resources/view/SupplyItemCard.fxml
Labels: priority.Medium, type.Task, severity.VeryLow

#167 Revert back to NFE exception handling
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/StatsCard.java
  src/main/java/seedu/address/ui/SupplyItemCard.java
Labels: priority.Medium, type.Bug, severity.Medium

#168 Fix for minor UG bug
  docs/UserGuide.md
Labels: priority.High, type.Bug, severity.Low

#169 Added inc dec stock feature in user guide
  docs/UserGuide.md
  docs/images/afterinc.png
  docs/images/greenstatuscard.png
  docs/images/incdeckeyin.png
  docs/images/labelledstatspanel.png
  docs/images/orangestatuscard.png
  docs/images/redstatuscard.png
Labels: priority.Medium, type.Task, Docs

#170 Update DG to show implementation of sorted TaskList
  docs/DeveloperGuide.md
  docs/diagrams/SortedTaskListActivityDiagramAddTask.puml
  docs/diagrams/SortedTaskListActivityDiagramUpdateTask.puml
  docs/images/SortedTaskListActivityDiagramAddTask.png
  docs/images/SortedTaskListActivityDiagramUpdateTask.png
Labels: priority.High, type.Task

#171 Update UG to show task can have multiple tags
  docs/UserGuide.md
Labels: priority.High, type.Task, Docs

#247 Fix UG bugs
  docs/UserGuide.md
Labels: priority.High, type.Bug, severity.VeryLow, Docs

#248 Fix bug where deleteTask does not work
  src/main/java/seedu/address/model/ModelManager.java
Labels: priority.High, type.Bug

#249 Fixed AddItem command parser bugs and small UG fix
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddItemCommand.java
  src/main/java/seedu/address/logic/parser/AddItemCommandParser.java
  src/test/java/seedu/address/logic/parser/AddItemCommandParserTest.java
Labels: priority.Medium

#250 Fix bug where elipsis is shown due to long text
  src/main/java/seedu/address/logic/parser/EditStockCommandParser.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/SupplyItemCard.java
  src/main/java/seedu/address/ui/TaskCard.java
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/SupplyItemCard.fxml
  src/main/resources/view/TaskListCard.fxml
Labels: priority.High, type.Task, type.Bug

#251 Improve handling of editStock
  src/main/java/seedu/address/logic/commands/EditStockCommand.java
  src/main/java/seedu/address/logic/parser/EditStockCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/EditStockCommandParserTest.java
Labels: priority.Medium, type.Bug, severity.VeryLow

#252 Update formatting and grammar in UG
  docs/UserGuide.md
Labels: priority.Medium, Docs

#254 UG bugfix for tag related components
  docs/UserGuide.md
  src/main/java/seedu/address/model/tag/Tag.java
Labels: priority.Medium, Docs
