Repository AY2223S1-CS2103T-W08-4/tp, pull requests merged in 2022-09, with the labels that each got.

#29 Update Jekyll site-wide settings
  docs/UserGuide.md
  docs/_config.yml
  docs/_sass/minima/_base.scss
Labels: priority.High, type.Task

#32 Update AboutUs
  docs/AboutUs.md
  docs/images/hauchongtang.png
Labels: priority.High, type.Task

#33 Update AboutUs
  docs/AboutUs.md
  docs/images/kang-quan.png
Labels: priority.High, type.Task

#51 Update AboutUs.md and Added Skeletal PPP
  docs/AboutUs.md
  docs/images/Bahamas20.png
  docs/team/bahamas20.md
Labels: priority.High

#53 Update README.md and index.md
  README.md
  docs/images/Ui.png
  docs/index.md
Labels: priority.High, type.Task

#54 Identity update
  docs/AboutUs.md
  docs/images/dreammac3816547290.png
  docs/team/dreammac3816547290.md
Labels: priority.High, type.Task

#57 Hotfix for for Product Page
  docs/AboutUs.md
  docs/images/bahamas20.png
  docs/images/johndoe.png
  docs/index.md
  docs/team/johndoe.md
Labels: priority.High, type.Bug, severity.Low

#59 Fixed some typos for AboutUs.Md
  docs/AboutUs.md
  docs/team/bahamas20.md
Labels: priority.High

#61 Changed typo from Salsey to Salesy for all files
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_config.yml
  docs/_sass/minima/_base.scss
  docs/index.md
  docs/team/hauchongtang.md
Labels: priority.Medium

#64 Attempt fix for toc
  docs/DeveloperGuide.md
Labels: priority.High, severity.Medium

#66 Attempt fix for UG TOC
  docs/UserGuide.md
Labels: priority.High, severity.Medium
